version: "2"

# Minimal golangci-lint configuration for this provider.
# Focus: correctness, DB/resource safety, and security.
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - errorlint
    - sqlclosecheck
    - rowserrcheck
    - gosec
    - nolintlint
