# Quick validation workflow for basic checks
name: Validate

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  fmt:
    name: Go Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted correctly:"
            gofmt -s -l .
            echo "Please run 'gofmt -s -w .' to format the code."
            exit 1
          fi

  vet:
    name: Go Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go vet ./...

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go test -v ./...
